[[main]]
  name = "Home"
  url = ""
  weight = 1

[[main]]
  name = "About"
  url = "about/"
  weight = 10

[[main]]
  name = "Algorithm"
  url = "post/algorithm/"
  weight = 2

[[main]]
  name = "Dev"
  url = "post/tech/"
  weight = 3

[[main]]
  name = "ML&DL"
  url = "post/mldl/"
  weight = 4

# social menu links

[[social]]
  name = "github"
  type = "social"
  weight = 1
  url = "https://github.com/Aiden-jeon"
[[social]]
  name = "linkedin"
  weight = 3
  url = "https://www.linkedin.com/in/jongseob-jeon/"

# other supported social links
# name = "youtube"
# url = "https://www.youtube.com/#"
# name = "facebook"
# url = "https://facebook.com/#"
# name = "instagram"
# url = "https://instagram.com/#"
# name = "stackoverflow"
# url = "https://stackoverflow.com/#"
# name = "gitlab"
# url = "https://gitlab.com/#"